#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_github_packages:
      - jimhester/covr
      after_success:
      - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: devel
    - os: linux
      r: release
      r_check_args: --as-cran --use-valgrind
      addons:
        apt:
          packages:
          - valgrind
      env: NB='w/ valgrind' ## Just a label
    - os: osx
      r: oldrel
      latex: false
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
      before_install:
      env: NB='w/out vignettes' ## Just a label
    - os: osx
      r: release
      latex: false
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --ignore-vignettes
      env: NB='w/out vignettes' ## Just a label
      before_install:
    
bioc_packages:
  - BiocInstaller
  - BiocGenerics
  - BiocStyle
  - IlluminaDataTestFiles

notifications:
  email:
    on_success: change
    on_failure: change
