#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
    - os: linux
      r: bioc-release
      r_check_args: --as-cran --use-valgrind
      addons:
        apt:
          packages:
          - valgrind
      env: NB='w/ valgrind' ## Just a label
    - os: osx
      r: bioc-release
      latex: false
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
      before_install:
      env: NB='w/out vignettes' ## Just a label
    - os: osx
      r: bioc-devel
      latex: false
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --ignore-vignettes
      env: NB='w/out vignettes' ## Just a label
      before_install:
    - os: linux
      r: bioc-release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    
bioc_packages:
  - BiocGenerics
  - BiocStyle
  - IlluminaDataTestFiles

notifications:
  email:
    on_success: change
    on_failure: change
